### ISSUE TITLE
CIT Resewn v1.2.0+1.21 Available!

### ISSUE THREAD

**Issue by personal-configuration** [DrBiznes/World-of-Wynncraft#1]
Hello! Love the pack! <3
I saw in your [collection](https://modrinth.com/collection/gs97WiAb) that you were planning to add [CIT Resewn](https://modrinth.com/mod/otVJckYQ) once it, and possibly the related resource pack(s) [Fables & Legends](https://modrinth.com/resourcepack/jAmyaRGD) and [Donjons](https://modrinth.com/resourcepack/Ys6nzWvS), saw the light of 1.21.x.
So I just wanted to remind you that all the things keep getting better ^-^
I'm hoping you keep making updates to your modpack...
It has been pretty awesome so far!

CIT Resewn for 1.21 is still in Beta of course though x-x ([changelog](https://modrinth.com/mod/cit-resewn/changelog)) [v1.2.1 + 1.21](https://modrinth.com/mod/cit-resewn/version/1.2.0+1.21)

**Comment by DrBiznes** [comment]
I should be releasing version 0.5 of the pack later today, I'll see if I can get CIT beta working for the release.

**Comment by DrBiznes** [comment]
I updated a few Wynncraft resourcepacks (Fables and Legends, Donjons, Wynncraft Overhaul, and Mythics Revivified) and sent them to the creators so hopefully they will upload the new versions tonight or tomorrow.

**Comment by DrBiznes** [comment]
The update should be out late tonight or tomorrow!

**Comment by DrBiznes** [comment]
Just updated the pack with the available resourcepacks I felt comfortable adding. I have a version of Fable and Legends and also Dunjons that is working but I didn't want to include them without permission from the author who hasn't responded to my discord messages yet.
