### ISSUE TITLE
cant connect on wynncraft

### ISSUE THREAD

**Issue by Novacfranz** [DrBiznes/World-of-Wynncraft#2]
**Describe the bug**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. Please upload crash logs if you crashed you can find them in the modpack folder under Crash-Reports

**Comment by DrBiznes** [comment]
Just pushed an update on modrinth I'll upload to other platforms later tonight
